### ISSUE TITLE
Gyro Simulation

### ISSUE THREAD

**Issue by ron-popov** [Rogozin-high-school/simulation_engine#1]
Lets start we a simple unity simulation that would read gyro data from the satellite and display it in 3D on a tv screen, that way we could start showing some progress to the rest of the school and the management and it probably won't take a lot of effort as most of the infrastructure (gyro hardware module) is already done.

**Comment by yotam180** [comment]
No problem at all! Let's talk about that tomorrow f2f.

**Comment by ron-popov** [comment]
I think we should start planning ahead so we could work on implementing everything tomorrow in the lab (there should be a drill tomorrow so it would cost us some lab time)

So first of all, how about communications ?  
First of all the communications will be over WIFI, we just need to decide what protocol.  
**HTTP** would be easy to implement since most of the code but it will be slower and won't give use that real-time effect.  
**UDP** might also be an option because if we would decide to aim for real-time, i think that we could score atleast 30 refreshes a second with UDP, and because the refresh rate is fairly high, if some packets gets lost and i don't think the packet loss would be noticable.  


I think we should use UDP due to it's higher response time, but i guess we should test it first to see if this is noticable.

**Comment by yotam180** [comment]
What drilling tomorrow? 

<hr/>

And about the TLP (Transport Level Protocol) I already wrote a communication module in C# that uses TCP. We can convert it to UDP, but I believe that for small but crucial amounts of data like we send (magnetorquer/Helmholtz coils commands) it's essentials that data is never corrupted.

Anyways I'm currently working on implementing the same protocol in Python. That way we will just be able to transport messages like that:

```
msg = Message(type, status)
msg.add_int(5)
msg.add_float(7.5)
```

And read them like that
```
Message msg = Server.NextMessage();
int first_parameter = msg.NextInt();
float second_parameter = msg.NextFloat();
```

Should be a very simple protocol to transfer our data. The C# side is (somehow) ready. Python message encoding and communication need to be implemented (in the `communication` branch on the @Rogozin-high-school/sat_monitoring_system)<sup>1</sup>

<hr/>

I have previously scored around 30 msgs/sec with TCP/IP (Scratch extension for Realsense Camera), but it was on a local machine. However I do think we can get to this rate with TCP too, when it's on lan and Ethernet. I believe UDP can reach a much higher frequency.

<hr/>

What do you think?

<sup>1</sup> How do I tag repositories and branches?

**Comment by ron-popov** [comment]
There should be a missle drill tommorow from 10:05 till 12:00, atleast it says so on the signs across school.

---

Of course, all of the satellite data communications should be done using TCP, i just meant for this mini experiment UDP might be better.  
BUT, if the TLP is ready and can be used for this purpose then sure, let's use it, i don't want to end up wasting too much time on this mini project.  

Any way, what i think we should do is like so, if we already have something that works lets use that, if we don't lets build a super simple communications system and hook it up the gyro module and unity simulation.

---

You could add a hyperlink to the repo ?
